### PR TITLE
Add auth_userokay

### PR DESCRIPTION
**Pull request by abexell**
This commit adds the authBSD auth_userokay call
and provides an example.

### CODE REVIEW

**Comment by n0la** [comment]
Please change the naming conventions to all lower case in function names, and add a cmake check for the function and this is good to go.

**Comment by abexell** [comment]
Thank you for your support. Function name corrected, checks added to CMake files.

**Comment by n0la** [comment]
Thanks, merged. Do you need a new tag too for ports@?

**Comment by qbit** [comment]
Yes please! :D

**Comment by n0la** [comment]
Done :)

**Comment by qbit** [comment]
updated the port: https://marc.info/?l=openbsd-ports-cvs&m=167389854522567&w=2

**Pull request merged**
